[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_referral = "6ssoCpKkRzcuVt2ZaHKe826HQsTZNLoYZCSQ6J8Sw6jS"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "localnet"
wallet = "/home/ancestor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
